# Form implementation generated from reading ui file 'finishWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(209, 133)
        Form.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.finish_frame = QtWidgets.QFrame(Form)
        self.finish_frame.setGeometry(QtCore.QRect(10, 10, 191, 111))
        self.finish_frame.setStyleSheet("QFrame#finish_frame {\n"
"    border: 1px solid black;\n"
"    border-radius:     15px;\n"
"}")
        self.finish_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.finish_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.finish_frame.setObjectName("finish_frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.finish_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 151, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_done = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_done.setFont(font)
        self.label_done.setStyleSheet("")
        self.label_done.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_done.setObjectName("label_done")
        self.gridLayout.addWidget(self.label_done, 0, 0, 1, 1)
        self.exit_push = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exit_push.setFont(font)
        self.exit_push.setObjectName("exit_push")
        self.gridLayout.addWidget(self.exit_push, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Finish"))
        self.label_done.setText(_translate("Form", "DONE"))
        self.exit_push.setText(_translate("Form", "EXIT"))
