# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(490, 370)
        MainMenu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"QFrame {\n"
"border: 3px solid black;\n"
"border-radius: 15px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 451, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.analyzer_push = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzer_push.sizePolicy().hasHeightForWidth())
        self.analyzer_push.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.analyzer_push.setFont(font)
        self.analyzer_push.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.analyzer_push.setObjectName("analyzer_push")
        self.gridLayout.addWidget(self.analyzer_push, 0, 1, 1, 1)
        self.onset_detector_push = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onset_detector_push.sizePolicy().hasHeightForWidth())
        self.onset_detector_push.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.onset_detector_push.setFont(font)
        self.onset_detector_push.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.onset_detector_push.setObjectName("onset_detector_push")
        self.gridLayout.addWidget(self.onset_detector_push, 0, 2, 1, 1)
        self.converter_push = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.converter_push.sizePolicy().hasHeightForWidth())
        self.converter_push.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.converter_push.setFont(font)
        self.converter_push.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.converter_push.setObjectName("converter_push")
        self.gridLayout.addWidget(self.converter_push, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 190, 451, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mass_analyzer_push = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mass_analyzer_push.sizePolicy().hasHeightForWidth())
        self.mass_analyzer_push.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mass_analyzer_push.setFont(font)
        self.mass_analyzer_push.setStyleSheet("")
        self.mass_analyzer_push.setObjectName("mass_analyzer_push")
        self.gridLayout_2.addWidget(self.mass_analyzer_push, 1, 1, 1, 1)
        self.mass_converter_push = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mass_converter_push.sizePolicy().hasHeightForWidth())
        self.mass_converter_push.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mass_converter_push.setFont(font)
        self.mass_converter_push.setStyleSheet("")
        self.mass_converter_push.setObjectName("mass_converter_push")
        self.gridLayout_2.addWidget(self.mass_converter_push, 0, 1, 1, 1)
        MainMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainMenu"))
        self.analyzer_push.setText(_translate("MainMenu", "ANALYZER"))
        self.onset_detector_push.setText(_translate("MainMenu", "ONSET\n"
"DETECTOR"))
        self.converter_push.setText(_translate("MainMenu", "CONVERTER"))
        self.mass_analyzer_push.setText(_translate("MainMenu", "MASS\n"
"ANALYZER"))
        self.mass_converter_push.setText(_translate("MainMenu", "MASS\n"
"CONVERTER"))
